### Define Logger config file directory ###
logging:
  config: classpath:log4j2-prd.yml
spring:
  config:
    import:
      - classpath:persistence-prd.yml

security:
  rememberme:
    # export REMEMBER_ME_KEY=$(openssl rand -hex 32)
    key: ${REMEMBER_ME_KEY:07490f81a5fcd9021d52e324963a901bc38a106df1de8ddb20aa7bcd04428f16}
    validity: 14d
