### Define Logger config file directory ###
logging:
  config: classpath:log4j2-dev.yml
spring:
  config:
    import:
      - classpath:persistence-dev.yml
### embedded Tomcat server settings ###
server:
  port: 8282
  servlet:
    context-path: /projectx
    session:
      timeout:
        72000s
